Config = Config or {}

Config.EngineSounds = {
    enabled = true,
    section = "engine_sounds",
    optionId = "engine_sound",
    cameraPart = "rear",

    engineUpgradeDefaults = {
        [1] = "Monster",
        [2] = "Cheetah",
        [3] = "Banshee"
    },
    sounds = {
        { audioName = "SULTAN2",     label = "Karin Sultan RS" },
        { audioName = "COMET4",      label = "Pfister Comet SR" },
        { audioName = "JUGULAR",     label = "Ocelot Jugular" },
        { audioName = "SCHAFTER3",   label = "Benefactor Schafter V12" },
        { audioName = "488SOUND",    label = "Ferrari 488" },
        { audioName = "F40V8",       label = "Ferrari F40 V8" },
        { audioName = "F50V12",      label = "Ferrari F50 V12" },
        { audioName = "FERRARIF12",  label = "Ferrari F12 V12" },
        { audioName = "LAMBOV10",            label = "Lamborghini V10" },
        { audioName = "PERFOV10",            label = "Huracán Performante V10" },
        { audioName = "SESTOV10",            label = "Sesto Elemento V10" },
        { audioName = "MURCIEV12",           label = "Murciélago V12" },
        { audioName = "LAMBO_AVENTADOR_V12", label = "Aventador V12" },
        { audioName = "LAMBO_VENENO_V12",    label = "Veneno V12" },
        { audioName = "LAMBO_COUNTACH_V12",  label = "Countach V12" },
        { audioName = "GT3FLAT6",    label = "Porsche GT3 Flat-6" },
        { audioName = "RH4",         label = "Porsche Boxer RH4" },
        { audioName = "LG157POR911", label = "Porsche 911 GT3 RS" },
        { audioName = "PORSCHE_V12", label = "Porsche Carrera V12" },
        { audioName = "AUDIRS4MILLTEKENG", label = "Audi RS4 Milltek" },
        { audioName = "AUDR8TTENG",         label = "Audi R8 Twin Turbo" },
        { audioName = "PRG25TFSI",          label = "Audi TT RS 2.5 TFSI" },
        { audioName = "AUDI_RS3_I5",        label = "Audi RS3 I5" },
        { audioName = "AUDI_RS4_V8",        label = "Audi RS4 V8" },
        { audioName = "AUDI_RS6_V8",        label = "Audi RS6 V8" },
        { audioName = "AUDI_RS7_2021",      label = "Audi RS7 (2021)" },
        { audioName = "AMG1ENG",    label = "Mercedes-AMG One" },
        { audioName = "M158HUAYRA", label = "AMG M158 V12" },
        { audioName = "ST11M156",   label = "AMG M156 V8" },
        { audioName = "ST31AT5",    label = "Mercedes M275 V12" },
        { audioName = "AMG_E55_V8", label = "Mercedes E55 AMG" },
        { audioName = "ST39E92",    label = "BMW M3 E92 V8" },
        { audioName = "STR021M3E30",label = "BMW M3 E30" },
        { audioName = "4AGE",       label = "Toyota 4A-GE" },
        { audioName = "A80FFENG",   label = "Toyota Supra 2JZ-GTE" },
        { audioName = "TOYSUPMK4",  label = "Toyota Supra MK4" },
        { audioName = "R35SOUND",   label = "Nissan GT-R R35" },
        { audioName = "HONDA_NSX_V6", label = "Honda NSX V6" },
        { audioName = "VIPERV10",    label = "Dodge Viper V10" },
        { audioName = "MUSV8",       label = "Ford Mustang V8" },
        { audioName = "ST18CHAR",    label = "Dodge Charger V8" },
        { audioName = "ST42CAMSS",   label = "Chevrolet Camaro SS" },
        { audioName = "STR4LS7",     label = "Corvette Z06 LS7" },
        { audioName = "KC98GMLS6SC", label = "GM LS6 Supercharged" },
        { audioName = "ROTARY7",     label = "Rotary 2.6L" },
        { audioName = "STR02213BT",  label = "Mazda RX-7 13B-TT" },
        { audioName = "VEYRONSOUND",  label = "Bugatti W16" },
        { audioName = "AQ88KOE50V8",  label = "Koenigsegg Agera" },
        { audioName = "PRGM158",      label = "Pagani Huayra M158" },
        { audioName = "DEIMOS",       label = "Deimos V12" },
        { audioName = "APOLLOSV8",    label = "Apollo V8" },
        { audioName = "ASTON_ZAGATO_V12", label = "Aston Martin Zagato V12" },
        { audioName = "2STRKBENG",    label = "2-Stroke Motorcycle" },
        { audioName = "HARLEY_VTWIN", label = "Harley-Davidson V-Twin" },
        { audioName = "K20A",            label = "Honda K20A" },
        { audioName = "URUSV8",          label = "Lamborghini Urus V8" },
        { audioName = "M297ZONDA",       label = "Pagani Zonda M297" },
        { audioName = "V8ENGINE",        label = "Generic V8" },
        { audioName = "SHONEN",          label = "Shonen I4 Turbo" },
        { audioName = "PREDATORV8",      label = "Ford Predator V8" },
        { audioName = "MCLARENV8",       label = "McLaren V8" },
        { audioName = "AVESVV12",        label = "Aventador SV V12" },
        { audioName = "NEBULA2",         label = "Volvo Nebula 2" },
        { audioName = "LG125MNSRYBENTLY",label = "Mansory Bentley W12" },
        { audioName = "ROXANNE",         label = "Roxanne V8" },
        { audioName = "ST47AF8C",        label = "Alfa Romeo 8C" },
        { audioName = "ST29B18CFNF",     label = "Mitsubishi Eclipse 4G63" },
        { audioName = "STR1520GDI",      label = "Ford Focus ST" },
        { audioName = "LEXUS_LFA_V10",   label = "Lexus LFA V10" },
    }
}
